name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: 'id_rsa_pem'
      - name: Add Acquia to known_hosts
        run: |
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa_pem
          { printf "free-8013.devcloud.hosting.acquia.com " & cat ~/.ssh/id_rsa_pem; } >> ~/.ssh/known_hosts
          ssh-keygen -Hf ~/.ssh/known_hosts
      - name: Push to Acquia Repository
        run: git push actiontest@svn-8018.devcloud.hosting.acquia.com:actiontest.git HEAD:master
