name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: 'id_rsa_pem'
      - name: Add Acquia to known_hosts
        run: |
          eval $(ssh-agent -s)
          printf "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh-add ~/.ssh/id_rsa_pem
          ssh-keyscan -t rsa free-8013.devcloud.hosting.acquia.com >> ~/.ssh/known_hosts
          ssh-keygen -Hf ~/.ssh/known_hosts
      - name: Push to Acquia Repository
        run: printf 'yes\n' | git push actiontest@svn-8018.devcloud.hosting.acquia.com:actiontest.git HEAD:master
