name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: 'id_rsa_gha'
      - name: Add Acquia to known_hosts
        run: |
          ssh-keyscan -t rsa free-8013.devcloud.hosting.acquia.com,3.230.0.80 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      - name: Push to Acquia Repository
        run: git push actiontest@svn-8018.devcloud.hosting.acquia.com:actiontest.git HEAD:master
      
#       - name: Configure SSH Keys
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
#         run: |
#           mkdir -p ~/.ssh
#           touch ~/.ssh/known_hosts
#           echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa_gha
#           cat ~/.ssh/id_rsa_gha
#           echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa_gha.pub
#           chmod 700 ~/.ssh
#           chmod 600 ~/.ssh/known_hosts
#           chmod 600 ~/.ssh/id_rsa_gha
#           eval $(ssh-agent)
#           ssh-add ~/.ssh/id_rsa_gha
#      
#       
