name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Configure SSH Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          mkdir $HOME/.ssh
          echo $SSH_PRIVATE_KEY > $HOME/.ssh/id_rsa_gha
          echo $SSH_PUBLIC_KEY > $HOME/.ssh/id_rsa_gha.pub
          ssh-add $HOME/.ssh/id_rsa_gha
      - name: Add Acquia to known_hosts
        run: ssh-keyscan -t rsa free-8013.devcloud.hosting.acquia.com >> $HOME/.ssh/known_hosts
      - name: Push to Acquia Repository
        run: git push actiontest@svn-8018.devcloud.hosting.acquia.com:actiontest.git HEAD:master
