name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push to Acquia Repository
        run: |
          ${{ ACQUIA_KNOWN_HOSTS }} >> /home/runner/.ssh/known_hosts
          git push actiontest@svn-8018.devcloud.hosting.acquia.com:actiontest.git HEAD:master
